# ===========================================================================
# Project:   Shokaku
# Copyright: ©2011 alexandru
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore

# SET UP PROXY
proxy "/posts", :to => "localhost:8080/posts"
