# ===========================================================================
# Project:   Shokaku
# Copyright: ©2011 alexandru
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore